name: Pull Request

on: pull_request

jobs:
  secrets:
    name: Secrets
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run secrets scan
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
        uses: GitGuardian/ggshield-action@master
        with:
          args: --verbose --all-policies

  security:
    name: Security
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Horusec
        run: curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
      - name: Run analysis
        run: |
          horusec start \
            --enable-commit-author="true" \
            --enable-git-history="true" \
            --enable-owasp-dependency-check="true" \
            --enable-shellcheck="true" \
            --information-severity="true" \
            --project-path="./" \
            --return-error="true" \
            --output-format="json" \
            --json-output-file="horusec.json"
      - name: Import report into DefectDojo
        run: |
          curl --request POST \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --header 'X-Api-Key: ${{ secrets.INTEGRATION_DEFECTDOJO }}' \
            --data "$(cat horusec.json)" \
            "https://api.appsec.orangestack.com/report?tool=horusec&env=${{ github.base_ref }}&repo=${{ github.repository }}"
        continue-on-error: true